name: SimpleSlider
version: @version@
main: click.seichi.simpleslider.SimpleSlider
depend: [WorldGuard, ItemNBTAPI]

commands:
  hoe:
    usage: /hoe
    description: This command gives a wooden hoe, whose NBT tags are customized, to the sender.

perimissions:
  simpleslider.hoe:
    default: true
