name: SimpleSlider
version: @version@
main: click.seichi.simpleslider.SimpleSlider
depend: [WorldGuard]

commands:
  hoe:
    usage: /hoe
    description: This is a hoe command.

perimissions:
  simpleslider.hoe:
    description: This Permission gives a wooden hoe sender.
    default: true