name: CI and CD

on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    uses: GiganticMinecraft/shared-workflows/.github/workflows/kotlin-ci.yaml@main
  cd:
    name: CD
    needs:
      - ci
    uses: GiganticMinecraft/shared-workflows/.github/workflows/kotlin-ci.yaml@main
    if: github.ref == 'refs/heads/main'
